---

- name: SB ASG - K8s EKS
  hosts: 127.0.0.1
  connection: local
  gather_facts: true

  vars:
      eks_prefix: eks-
      scaling_version: 202001261129

  vars_files:
    - "vars/k8s-cluster/eks-cloud-{{ env }}.yml"

  vars_prompt:
    - name: "asg_var"
      prompt: "What AWS ASG FILE do you want to load [vars/k8s-cluster/aws-asg/<FILE>.yml or * to ALL]?"
      private: no
      when: asg_var is not defined

  pre_tasks:
    - name: Fix hostname issues on RHEL
      set_fact:
        eks_ec2_userdata: |
          {{ eks_ec2_userdata }}

          ## Force cloud init to preserve hostname
          hostnamectl set-hostname \
            --static \
            --pretty \
            --transient \
            $(hostname  |awk -F'ec2.internal' '{print$1}')ec2.internal;
          systemctl restart kubelet
      tags: always

    - block:
      - name: Load AWS ASG definitions from vars/k8s-cluster/aws-asg
        include_vars: "{{ item }}"
        with_items:
          - "{{ playbook_dir }}/vars/k8s-cluster/aws-asg/{{ asg_var }}.yml"
        tags: always

      when: asg_var != "*"

    - block:
      - name: Load all AWS ASG  definitions from vars/k8s-cluster/aws-asg
        include_vars: "{{ item }}"
        with_fileglob:
          - "{{ playbook_dir }}/vars/k8s-cluster/aws-asg/*.yml"

      when: asg_var == "*"

  roles:
    - role: ec2-scaling.sb
      tags: scale